spring:
  cache:
    type: redis
    redis:
      time-to-live: PT1H
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOSTNAME}:${MONGODB_PORT}/${MONGODB_NAME}?authSource=admin
      auto-index-creation: true
      authentication-database: admin
    redis:
      host: ${REDIS_HOSTNAME:localhost}
      port: ${REDIS_PORT:63792}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${POSTGRES_DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  task:
    scheduling:
      enable: true

job-offers:
  offer:
    fetcher:
      port: 5057
      uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
    rest-template-config:
      connection-time-out: 5000
      read-time-out: 5000
    scheduler:
      fixed-rate: PT1H
      enable: true
  user:
    auth:
      jwt:
        expirationTimeInMs: 1209600000
        secret: ${JWT_SECRET}
        issuer: job-offers-backend
