version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0
  aws-cli: circleci/aws-cli@4.0

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run:
          name: Installing Project by Maven
          command: mvn install -DskipTests
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Run Tests
          command: mvn test
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - aws-ecr/build_and_push_image:
          attach_workspace: true
          context: aws-dev
          requires:
            - test
            - build
          dockerfile: Dockerfile
          path: .
          repo: job-offers
          workspace_root: .

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
