version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Installing Project by Maven
          command: mvn install -DskipTests
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Run Tests
          command: mvn test
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
