version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run:
          name: Installing Project by Maven
          command: mvn install -DskipTests
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - attach_workspace:
          at: .
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Run Tests
          command: mvn test
      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  sample:
    jobs:
      - build
      - test:
          requires:
            - build
      - aws-ecr/build-and-push-image:
          context: aws-dev
          requires:
            - test
          dockerfile: Dockerfile
          path: .
          repo: job-offers
          tag: "$CIRCLE_SHA1" # default - latest
