version: 2.1
orbs:
  qodana: jetbrains/qodana@2024.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Installing Project by Maven
          command: mvn install -DskipTests
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Run Tests
          command: mvn test
      - persist_to_workspace:
          root: .
          paths:
            - .

  code-quality:
    machine:
      image: 'ubuntu-2004:current'
    steps:
      - checkout
      - qodana/scan:
          args: -l jetbrains/qodana-jvm

workflows:
  build-test-codeQuality:
    jobs:
      - build
      - test:
          requires:
            - build
      - code-quality:
          context: qodana
