name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Możesz też użyć 'zulu' lub 'oracle'
          java-version: '21'

      - name: Install Project dependencies using Maven
        run: mvn install -DskipTests

      - name: Persist workspace
        run: |
          mkdir -p $GITHUB_WORKSPACE/build
          cp -r .. $GITHUB_WORKSPACE/build

  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Restore workspace
        run: |
          cp -r $GITHUB_WORKSPACE/build/* .

      - name: Set up Docker for testing
        uses: docker/setup-buildx-action@v2
        with:
          version: 20.10.14

      - name: Run Tests
        run: mvn test
